<?php
/**
 * @package drupal
 * @subpackage droksidemenu
 * @version 6.x-1.1 June 3, 2010
 * @author RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2010 RocketTheme, LLC
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
/*====================================
	dRokSideMenu Navigation Module
====================================*/

/*
* Implementation of hook_block()
*/

function droksidemenu_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
	
		case 'list':
			$blocks[0]['info'] = t('dRokSideMenu');
			$blocks[0]['cache'] = BLOCK_NO_CACHE;
			return $blocks;
			break;
		
		// configure items on block admin page
		case 'configure':
		case 'save':
			break;
		case 'view':

            $links = menu_tree_page_data('primary-links');
            $block['subject'] = variable_get("droksidemenu_title", t('Main Menu'));
			$block['content'] = theme('droksidemenu', $links);
			return $block;
			break;
	}

}

function droksidemenu_theme() {
  return array(
    'droksidemenu' => array(
      'template' => 'droksidemenu',
      'arguments' => array('links' => array()),
    ),
  );
}

function droksidemenu_admin() {
	
	$form = array();
	
	$form['droksidemenu_title'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Menu Title'),
	    '#default_value' => variable_get('droksidemenu_title', 'Main Menu'),
	    '#size' => 20,
	    '#maxlength' => 20,
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  	
	  return system_settings_form($form);
}

function droksidemenu_menu() {

	$items = array();
	
	$items['admin/rockettheme'] = array(
		'title' => 'RocketTheme',
		'description' => 'Manage settings for custom RocketTheme Modules.',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	
	);
	
	
	$items['admin/rockettheme/droksidemenu'] = array(
	'title' => 'dRokSideMenu ',
	'description' => 'Administer settings for dRokSideMenu',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('droksidemenu_admin'),
	'access arguments' => array('access administration pages'),
	'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
}


