<?php
/**
 * @package drupal
 * @subpackage droktabs
 * @version 6.x-1.2 October 12, 2010
 * @author RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2010 RocketTheme, LLC
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */
/*====================================
	droktabs Module
====================================*/

/*
* Implementation of hook_block()
*/

function droktabs_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
	
		case 'list':
			$blocks[0]['info'] = t('dRokTabs');
			$blocks[0]['cache'] = BLOCK_NO_CACHE;
			return $blocks;
			break;
		
		// configure items on block admin page
		case 'configure':
		case 'save':
			break;
		case 'view':

            $block['subject'] = "";
			$block['content'] = theme('droktabs');
			return $block;
			break;
	}

}

function droktabs_theme() {
  return array(
    'droktabs' => array(
      'template' => 'droktabs',
      'arguments' => array('links' => array()),
    ),
  );
}

function droktabs_admin() {
	
	$form = array();
	
	$form['droktabs_rotatorCount'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Maximum number of articles to retrieve'),
	    '#default_value' => variable_get('droktabs_rotatorCount', 6),
	    '#size' => 4,
	    '#maxlength' => 4,
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	   $form['droktabs_category'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Category ID'),
	    '#size' => 4,
	    '#maxlength' => 4,
	    '#default_value' => variable_get('droktabs_category', ''),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droktabs_width'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Width'),
	    '#default_value' => variable_get('droktabs_width', 500),
	    '#size' => 6,
	    '#maxlength' => 6,
	    '#required' => TRUE,
	  );
	  
	  
	  $form['droktabs_duration'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Transition Duration'),
	    '#default_value' => variable_get('droktabs_duration', 600),
	    '#size' => 6,
	    '#maxlength' => 6,
	    '#required' => TRUE,
	  );
	  
	  $form['droktabs_transition'] = array(
	    '#type' => 'select',
	    '#title' => t('Transition'),
			'#options' => array(
				'linear' => 'linear',
				'Quad.easeOut' => 'Quad.easeOut',
				'Quad.easeIn' => 'Quad.easeIn',
				'Quad.easeInOut' => 'Quad.easeInOut',
				'Cubic.easeOut' => 'Cubic.easeOut',
				'Cubic.easeIn' => 'Cubic.easeIn',
				'Cubic.easeInOut' => 'Cubic.easeInOut',
				'Quart.easeOut' => 'Quart.easeOut',
				'Quart.easeIn' => 'Quart.easeIn',
				'Quart.easeInOut' => 'Quart.easeInOut',
				'Quint.easeOut' => 'Quint.easeOut',
				'Quint.easeIn' => 'Quint.easeIn',
				'Quint.easeInOut' => 'Quint.easeInOut',
				'Expo.easeOut' => 'Expo.easeOut',
				'Expo.easeIn' => 'Expo.easeIn',
				'Expo.easeInOut' => 'Expo.easeInOut',
				'Circ.easeOut' => 'Circ.easeOut',
				'Circ.easeIn' => 'Circ.easeIn',
				'Circ.easeInOut' => 'Circ.easeInOut',
				'Sine.easeOut' => 'Sine.easeOut',
				'Sine.easeIn' => 'Sine.easeIn',
				'Sine.easeInOut' => 'Sine.easeInOut',
				'Back.easeOut' => 'Back.easeOut',
				'Back.easeIn' => 'Back.easeIn',
				'Back.easeInOut' => 'Back.easeInOut',
				'Bounce.easeOut' => 'Bounce.easeOut',
				'Bounce.easeIn' => 'Bounce.easeIn',
				'Bounce.easeInOut' => 'Bounce.easeInOut',
				'Elastic.easeOut' => 'Elastic.easeOut',
				'Elastic.easeIn' => 'Elastic.easeIn',
				'Elastic.easeInOut' => 'Elastic.easeInOut',
				),
	    '#default_value' => variable_get('droktabs_transition', "Quad.easeInOut"),
	  );
	  
	  
	  $form['droktabs_autoplay'] = array(
	    '#type' => 'select',
	    '#title' => t('Auto Play'),
	    '#options' => array(
			'1' => 'Yes',
			'0' => 'No'
		),
	    '#default_value' => variable_get('droktabs_autoplay', 0),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droktabs_delay'] = array(
	    '#type' => 'textfield',
	    '#title' => t('Autoplay Delay'),
	    '#default_value' => variable_get('droktabs_delay', 2000),
	    '#size' => 6,
	    '#maxlength' => 6,
	    '#required' => TRUE,
	  );
	  
	  $form['droktabs_type'] = array(
	    '#type' => 'select',
	    '#title' => t('Transition Type'),
	    '#options' => array(
			'scrolling' => 'Scrolling',
			'fading' => 'Fading'
		),
	    '#default_value' => variable_get('droktabs_type', 0),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );
	  
	  $form['droktabs_link_margins'] = array(
	    '#type' => 'select',
	    '#title' => t('Subtract links margins'),
	    '#options' => array(
			'1' => 'Yes',
			'0' => 'No'
		),
	    '#default_value' => variable_get('droktabs_link_margins', 0),
	    //'#description' => t(""),
	    '#required' => TRUE,
	  );

	
	  return system_settings_form($form);
}

function droktabs_menu() {

	$items = array();
	
	$items['admin/rockettheme'] = array(
		'title' => 'RocketTheme',
		'description' => 'Manage settings for custom RocketTheme Modules.',
		'position' => 'right',
		'weight' => -5,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	
	);
	
	
	$items['admin/rockettheme/droktabs'] = array(
	'title' => 'dRokTabs ',
	'description' => 'Administer settings for dRokTabs',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('droktabs_admin'),
	'access arguments' => array('access administration pages'),
	'type' => MENU_NORMAL_ITEM,
	);
	
	return $items;
	
}

